---
apiVersion: v1
kind: Namespace
metadata:
  name: rc
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rc-secrets
  namespace: rc
spec:
  releaseName: secrets
  targetNamespace: rc
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm/
    name: create-secret-manager-secret
    version: 0.0.4
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/rc/rcSecrets.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rc-datarepo
  namespace: rc
spec:
  releaseName: rc-jade
  targetNamespace: rc
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm/
    name: datarepo
    version: 0.0.4
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/rc/rcDeployment.yaml
