## Be sure to add the helm repos
## helm repo add datarepo-helm https://broadinstitute.github.io/datarepo-helm && helm repo update
apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: gcr.io/broad-jade-dev/jade-data-repo
    jib:
      args:
      - jib
      type: gradle
deploy:
  helm:
    flags:
      upgrade:
        - --install
        - --debug
    releases:
    # create secrets
    - name: eo-jade-create-secret-manager-secret
      chartPath: datarepo-helm/create-secret-manager-secret
      namespace: eo
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/eo/create-secret-manager-secret.yaml
    # gcp sqlproxy
    - name: eo-jade-gcloud-sqlproxy
      chartPath: datarepo-helm/gcloud-sqlproxy
      namespace: eo
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/eo/gcloud-sqlproxy.yaml
    # datarepo-api
    - name: eo-jade-datarepo-api
      chartPath: datarepo-helm/datarepo-api
      namespace: eo
      remote: true
      values:
        imageName: gcr.io/broad-jade-dev/jade-data-repo
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/eo/datarepo-api.yaml
    # datarepo-ui
    - name: eo-jade-datarepo-ui
      chartPath: datarepo-helm/datarepo-ui
      namespace: eo
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/eo/datarepo-ui.yaml
    # oidc-proxy
    - name: eo-jade-oidc-proxy
      chartPath: datarepo-helm/oidc-proxy
      namespace: eo
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/eo/oidc-proxy.yaml
