gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
    - instance: "jade-postgres-101-d0e234edfe378f09" # GCP instance name.
      # GCP project where the instance exists.
      project: "broad-jade-integration"
      # GCP region where the instance exists.
      region: "us-central1"
      # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-integration-5
  existingSecretKey: sa
datarepo-api:
  enabled: true
  image:
    tag: a35435d
  env:
    GOOGLE_PROJECTID: broad-jade-integration
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://integration-5-jade-gcloud-sqlproxy.integration-5:5432/stairway-5
    DB_DATAREPO_URI: jdbc:postgresql://integration-5-jade-gcloud-sqlproxy.integration-5:5432/datarepo-5
    IT_JADE_API_URL: https://jade-5.datarepo-integration.broadinstitute.org
    DATAREPO_GCS_ALLOWREUSEEXISTINGBUCKETS: true
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-integration-5"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
datarepo-ui:
  enabled: true
  image:
    tag: 7918981
  proxyPass:
    status: http://integration-5-jade-datarepo-api.integration-5:8080/status
    swagger: http://integration-5-jade-datarepo-api.integration-5:8080/swagger-ui.html
    api: http://integration-5-jade-datarepo-api.integration-5:8080
  serviceAccount:
    create: true
  rbac:
    create: true
oidc-proxy:
  enabled: true
  replicaCount: 1
  env:
    PROXY_URL: http://integration-5-jade-datarepo-ui.integration-5:80/
    PROXY_URL2: http://integration-5-jade-datarepo-api.integration-5:8080/api
    PROXY_URL3: http://integration-5-jade-datarepo-api.integration-5:8080/register
    LOG_LEVEL: debug
    SERVER_NAME: jade.datarepo-integration.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript
      application/x-javascript
  ingress:
    enabled: true
    annotations:
      globalStaticIpName: integration-ip-5
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingTlsSecret: oidc-tls-key
