## rc env specific skaffold.yaml
apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: gcr.io/broad-jade-dev/jade-data-repo
    jib:
      args:
      - jib
      type: gradle
deploy:
  helm:
    flags:
      upgrade:
        - --install
        - --debug
    releases:
# create secrets
    - name: rc-jade-create-secret-manager-secret
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/create-secret-manager-secret-0.0.4/create-secret-manager-secret-0.0.4.tgz
      version: 0.0.5
      namespace: rc
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/rc/create-secret-manager-secret.yaml
# gcp sqlproxy
    - name: rc-jade-gcloud-sqlproxy
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/gcloud-sqlproxy-0.19.7/gcloud-sqlproxy-0.19.7.tgz
      version: 0.19.7
      namespace: rc
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/rc/gcloud-sqlproxy.yaml
# datarepo-api
    - name: rc-jade-datarepo-api
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/datarepo-api-0.0.17/datarepo-api-0.0.17.tgz
      version: 0.0.17
      namespace: rc
      remote: true
      values:
        imageName: gcr.io/broad-jade-dev/jade-data-repo
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/rc/datarepo-api.yaml
# datarepo-ui
    - name: rc-jade-datarepo-ui
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/datarepo-ui-0.0.8/datarepo-ui-0.0.8.tgz
      version: 0.0.8
      namespace: rc
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/rc/datarepo-ui.yaml
# oidc-proxy
    - name: rc-jade-oidc-proxy
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/oidc-proxy-0.0.9/oidc-proxy-0.0.9.tgz
      version: 0.0.9
      namespace: rc
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/rc/oidc-proxy.yaml
