#TODO BEFORE RUNNING
# Copy over to jade-data-repo-ui folder and change name to "skaffold.yaml"
# Then can run "skaffold run"
apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: gcr.io/broad-jade-dev/jade-data-repo-ui
    docker:
      buildArgs:
        ENV: production
deploy:
  helm:
    flags:
      upgrade:
        - --install
        - --debug
    releases:
    # create secrets
    - name: sh-jade-create-secret-manager-secret
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/create-secret-manager-secret-0.0.6/create-secret-manager-secret-0.0.6.tgz
      version: 0.0.6
      namespace: sh
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/sh/create-secret-manager-secret.yaml
    # gcp sqlproxy
    - name: sh-jade-gcloud-sqlproxy
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/gcloud-sqlproxy-0.19.7/gcloud-sqlproxy-0.19.7.tgz
      version: 0.19.7
      namespace: sh
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/sh/gcloud-sqlproxy.yaml
    # datarepo-api
    - name: sh-jade-datarepo-api
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/datarepo-api-0.0.23/datarepo-api-0.0.23.tgz
      version: 0.0.23
      namespace: sh
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/sh/datarepo-api.yaml
    # datarepo-ui
    - name: sh-jade-datarepo-ui
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/datarepo-ui-0.0.12/datarepo-ui-0.0.12.tgz
      version: 0.0.12
      namespace: sh
      remote: true
      values:
        imageName: gcr.io/broad-jade-dev/jade-data-repo-ui
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/sh/datarepo-ui.yaml
    # oidc-proxy
    - name: sh-jade-oidc-proxy
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/oidc-proxy-0.0.14/oidc-proxy-0.0.14.tgz
      version: 0.0.14
      namespace: sh
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/sh/oidc-proxy.yaml
