---
apiVersion: v1
kind: Namespace
metadata:
  name: integration
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: integration-secrets
  namespace: integration
spec:
  releaseName: secrets
  targetNamespace: integration
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm/
    name: create-secret-manager-secret
    version: 0.0.4
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/integration/integration/integrationSecrets.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: integration-datarepo
  namespace: integration
spec:
  releaseName: integration-jade
  targetNamespace: integration
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm/
    name: datarepo
    version: 0.0.5
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/integration/integration/integrationDeployment.yaml
