gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
     # GCP instance name.
    - instance: "jade-postgres-101-d0e234edfe378f09"
     # GCP project where the instance exists.
      project: "broad-jade-integration"
     # GCP region where the instance exists.
      region: "us-central1"
     # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-integration
  existingSecretKey: sa

datarepo-api:
  enabled: true
  image:
    tag: 43446c5-develop
  env:
    googleProjectid:  broad-jade-integration
    dbDatarepoUsername:  drmanager
    springProfilesActive:  google,cloudsql,integration
    dbStairwayUsername:  drmanager
    dbStairwayUri: jdbc:postgresql://integration-jade-gcloud-sqlproxy.integration:5432/stairway-integration
    dbDatarepoUri: jdbc:postgresql://integration-jade-gcloud-sqlproxy.integration:5432/datarepo-integration
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-integration"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"

datarepo-ui:
  enabled: true
  image:
    tag: broad-jade-my_2020-02-14_15-04-11
  proxyPass:
    status: http://integration-jade-datarepo-api.integration:8080/status
    swagger: http://integration-jade-datarepo-api.integration:8080/swagger-ui.html
    api: http://integration-jade-datarepo-api.integration:8080
  serviceAccount:
    create: true
  rbac:
    create: true

oidc-proxy:
  enabled: true
  env:
    proxyUrl: http://integration-jade-datarepo-ui.integration:80/
    proxyUrl2: http://integration-jade-datarepo-api.integration:8080/api
    proxyUrl3: http://integration-jade-datarepo-api.integration:8080/register
    logLevel: debug
    serverName: jade.datarepo-integration.broadinstitute.org
    remoteUserClaim: sub
    enableStackdriver: yes
    filter2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
  ingress:
    enabled: true
    annotations:
      globalStaticIpName: jade-k8-100
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingTlsSecret: oidc-tls-key
