---
repositories:
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

  - name: datarepo-helm-local
    url: http://localhost:8000

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

# helm releases to be deployed
releases:
  - name: datarepo-monitoring-secret   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/create-secret-manager-secret   # chart name
    version: 0.0.6
    missingFileHandler: Warn
    values:
      - create-secret-manager-secret.yaml

  - name: datarepo-monitoring-backend-config   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/backend-config   # chart name
    version: 0.1.0
    missingFileHandler: Warn

  - name: datarepo-monitoring-frontend-config   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/frontend-config   # chart name
    version: 0.1.0
    missingFileHandler: Warn

  - name: grafana-gcp-managed-cert   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/gcp-managed-cert   # chart name
    version: 0.1.3
    missingFileHandler: Warn
    values:
      - fullnameOverride: grafana-gcp-managed-cert
      - domainName: grafana.datarepo-dev.broadinstitute.org

  - name: datarepo-monitoring   # release name
    namespace: monitoring   # target namespace
    chart: prometheus-community/kube-prometheus-stack   # chart name
    version: 13.13.0   # chart version pin
    missingFileHandler: Warn
    values:
      - kube-prometheus-stack.yaml
