# single env example file
# helm file dependencies
# helm plugin install https://github.com/databus23/helm-diff
# repositories to be installed
repositories:
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

# helm releases to be deployed
releases:
  - name: descheduler   # release name
    namespace: kube-system   # target namespace
    chart: descheduler/descheduler   # chart name
    version: v0.20.0 # chart version (note more recent charts break)
    missingFileHandler: Warn
    values:
      - schedule: "0 * * * *"
  - name: terra-jade-gcloud-sqlproxy    # release name
    namespace: data-repo   # target namespace
    createNamespace: true
    chart: datarepo-helm/gcloud-sqlproxy   # chart name
    version: 0.19.7 #    Chart version
    missingFileHandler: Warn
    values:
      - gcloud-sqlproxy.yaml    # Value files passed via --values
  - name: terra-jade-datarepo-api   # name of this release
    namespace: data-repo   # target namespace
    createNamespace: true
    chart: datarepo-helm/datarepo-api   # the chart name
    version: 0.0.140    # chart version
    missingFileHandler: Warn
    values:
      - datarepo-api.yaml   # Value files passed via --values
  - name: terra-jade-datarepo-ui   # name of this release
    namespace: data-repo   # target namespace
    createNamespace: true
    chart: datarepo-helm/datarepo-ui   # the chart name
    version: 0.0.78    # chart version
    missingFileHandler: Warn
    values:
      - datarepo-ui.yaml   # Value files passed via --values
  - name: terra-jade-oidc-proxy   # name of this release
    namespace: data-repo   # target namespace
    createNamespace: true
    chart: datarepo-helm/oidc-proxy   # the chart name
    version: 0.0.24    # chart version
    missingFileHandler: Warn
    values:
      - oidc-proxy.yaml   # Value files passed via --values
