# single env example file
# helm file dependencies
# helm plugin install https://github.com/databus23/helm-diff
# repositories to be installed
repositories:
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

helmDefaults:
  createNamespace: true

# helm releases to be deployed
releases:
  - name: perf-jade-create-secret-manager-secret    # release name
    namespace: perf   # target namespace
    chart: datarepo-helm/create-secret-manager-secret   # chart name
    version: 0.0.6   #    Chart version
    missingFileHandler: Warn
    values:
      - datarepo/create-secret-manager-secret.yaml      # Value files passed via --values
  - name: perf-jade-gcloud-sqlproxy    # release name
    namespace: perf   # target namespace
    chart: datarepo-helm/gcloud-sqlproxy   # chart name
    version: 0.19.7 #    Chart version
    missingFileHandler: Warn
    values:
      - datarepo/gcloud-sqlproxy.yaml    # Value files passed via --values
  - name: perf-jade-datarepo-api   # name of this release
    namespace: perf   # target namespace
    chart: datarepo-helm/datarepo-api   # the chart name
    version: 0.0.25    # chart version
    missingFileHandler: Warn
    values:
      - datarepo/datarepo-api.yaml   # Value files passed via --values
  - name: perf-jade-datarepo-ui   # name of this release
    namespace: perf   # target namespace
    chart: datarepo-helm/datarepo-ui   # the chart name
    version: 0.0.13    # chart version
    missingFileHandler: Warn
    values:
      - datarepo/datarepo-ui.yaml   # Value files passed via --values
  - name: perf-jade-oidc-proxy   # name of this release
    namespace: perf   # target namespace
    chart: datarepo-helm/oidc-proxy   # the chart name
    version: 0.0.17    # chart version
    missingFileHandler: Warn
    values:
      - datarepo/oidc-proxy.yaml   # Value files passed via --values
# datarepomonitoring
  - name: datarepomonitoring   # release name
    namespace: monitoring   # target namespace
    version: 0.0.2
    chart: datarepo-helm/datarepomonitoring   # chart name
    missingFileHandler: Warn
    values:
      - datarepomonitoring/datarepomonitoring.yaml
