repositories:
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  createNamespace: true

# helm releases to be deployed
releases:
  - name: descheduler   # release name
    namespace: kube-system   # target namespace
    chart: descheduler/descheduler   # chart name
    version: v0.20.0 # chart version (note more recent charts break)
    missingFileHandler: Warn
    values:
      - schedule: "0 * * * *"

  - name: perf-jade-create-secret-manager-secret    # release name
    namespace: perf   # target namespace
    chart: datarepo-helm/create-secret-manager-secret   # chart name
    version: 0.0.6   #    Chart version
    missingFileHandler: Warn
    values:
      - datarepo/create-secret-manager-secret.yaml      # Value files passed via --values

  - name: perf-jade-gcloud-sqlproxy    # release name
    namespace: perf   # target namespace
    chart: datarepo-helm/gcloud-sqlproxy   # chart name
    version: 0.19.7 #    Chart version
    missingFileHandler: Warn
    values:
      - datarepo/gcloud-sqlproxy.yaml    # Value files passed via --values

  - name: perf-jade-datarepo-api   # name of this release
    namespace: perf   # target namespace
    chart: datarepo-helm/datarepo-api   # the chart name
    missingFileHandler: Warn
    values:
      - datarepo/datarepo-api.yaml   # Value files passed via --values

  - name: perf-jade-datarepo-ui   # name of this release
    namespace: perf   # target namespace
    chart: datarepo-helm/datarepo-ui   # the chart name
    missingFileHandler: Warn
    values:
      - datarepo/datarepo-ui.yaml   # Value files passed via --values

  - name: perf-jade-oidc-proxy   # name of this release
    namespace: perf   # target namespace
    chart: datarepo-helm/oidc-proxy   # the chart name
    version: 0.0.25    # chart version
    missingFileHandler: Warn
    values:
      - datarepo/oidc-proxy.yaml   # Value files passed via --values
# datarepomonitoring
  - name: datarepomonitoring-secret   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/create-secret-manager-secret   # chart name
    version: 0.0.6
    missingFileHandler: Warn
    values:
      - datarepomonitoring/create-secret-manager-secret.yaml

  - name: datarepomonitoring-backend-config   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/backend-config   # chart name
    version: 0.1.0
    missingFileHandler: Warn

  - name: grafana-gcp-managed-cert   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/gcp-managed-cert   # chart name
    version: 0.1.3
    missingFileHandler: Warn
    values:
      - fullnameOverride: grafana-gcp-managed-cert
      - domainName: datarepo-grafana.datarepo-perf.broadinstitute.org

  - name: prometheus-gcp-managed-cert   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/gcp-managed-cert   # chart name
    version: 0.1.3
    missingFileHandler: Warn
    values:
      - fullnameOverride: prometheus-gcp-managed-cert
      - domainName: datarepo-prometheus.datarepo-perf.broadinstitute.org

  - name: datarepomonitoring   # release name
    namespace: monitoring   # target namespace
    chart: prometheus-community/kube-prometheus-stack   # chart name
    version: 13.13.0   # chart version pin
    missingFileHandler: Warn
    values:
      - datarepomonitoring/kube-prometheus-stack.yaml
