---
gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
      # GCP instance name.
      - instance: "jade-postgres-101-987f0c3b501aeabf"
        # GCP project where the instance exists.
        project: "broad-jade-dev"
        # GCP region where the instance exists.
        region: "us-central1"
        # Port number for the proxy to expose for this instance.
        port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-mk
  existingSecretKey: sa

datarepo-api:
  enabled: true
  image:
    tag: 1ae0923
  env:
    GOOGLE_PROJECTID: broad-jade-my
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql,mk
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://mk-jade-gcloud-sqlproxy.mk:5432/stairway-mk
    DB_DATAREPO_URI: jdbc:postgresql://mk-jade-gcloud-sqlproxy.mk:5432/datarepo-mk
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-mk"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"

datarepo-ui:
  enabled: true
  image:
    tag: broad-jade-my_2020-02-14_15-04-11
  proxyPass:
    status: http://mk-jade-datarepo-api.mk:8080/status
    swagger: http://mk-jade-datarepo-api.mk:8080/swagger-ui.html
    api: http://mk-jade-datarepo-api.mk:8080
  serviceAccount:
    create: true
  rbac:
    create: true

oidc-proxy:
  enabled: true
  env:
    PROXY_URL: http://mk-jade-datarepo-ui.mk:80/
    PROXY_URL2: http://mk-jade-datarepo-api.mk:8080/api
    PROXY_URL3: http://mk-jade-datarepo-api.mk:8080/register
    LOG_LEVEL: debug
    SERVER_NAME: jade.datarepo-dev.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
  ingress:
    enabled: true
    annotations:
      globalStaticIpName: jade-dev-mk
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingTlsSecret: oidc-tls-key
