gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
    - instance: "jade-postgres-101-d0e234edfe378f09" # GCP instance name.
      # GCP project where the instance exists.
      project: "broad-jade-integration"
      # GCP region where the instance exists.
      region: "us-central1"
      # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-integration-2
  existingSecretKey: sa
datarepo-api:
  enabled: true
  image:
    tag: a35435d
  env:
    googleProjectid: broad-jade-int-2
    dbDatarepoUsername: drmanager
    springProfilesActive: google,cloudsql,integration
    dbStairwayUsername: drmanager
    dbStairwayUri: jdbc:postgresql://integration-2-jade-gcloud-sqlproxy.integration-2:5432/stairway-2
    dbDatarepoUri: jdbc:postgresql://integration-2-jade-gcloud-sqlproxy.integration-2:5432/datarepo-2
    itJadeApiUrl: https://jade-2.datarepo-integration.broadinstitute.org
    datarepoGcsAllowreuseexistingbuckets: true
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-integration-2"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
datarepo-ui:
  enabled: true
  image:
    tag: 7918981
  proxyPass:
    status: http://integration-2-jade-datarepo-api.integration-2:8080/status
    swagger: http://integration-2-jade-datarepo-api.integration-2:8080/swagger-ui.html
    api: http://integration-2-jade-datarepo-api.integration-2:8080
  serviceAccount:
    create: true
  rbac:
    create: true
oidc-proxy:
  enabled: true
  replicaCount: 1
  env:
    proxyUrl: http://integration-2-jade-datarepo-ui.integration-2:80/
    proxyUrl2: http://integration-2-jade-datarepo-api.integration-2:8080/api
    proxyUrl3: http://integration-2-jade-datarepo-api.integration-2:8080/register
    logLevel: debug
    serverName: jade.datarepo-integration.broadinstitute.org
    remoteUserClaim: sub
    enableStackdriver: yes
    filter2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript
      application/x-javascript
  ingress:
    enabled: true
    annotations:
      globalStaticIpName: integration-ip-2
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingTlsSecret: oidc-tls-key
