---
repositories:
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

helmDefaults:
  createNamespace: true

# helm releases to be deployed
releases:
  - name: datarepomonitoring   # release name
    namespace: monitoring   # target namespace
    createNamespace: true
    chart: datarepo-helm/datarepomonitoring   # chart name
    version: 0.0.2
    missingFileHandler: Warn
    values:
      - datarepomonitoring/datarepomonitoring.yaml
  - name: psqlbackup   # release name
    namespace: psqlbackup   # target namespace
    createNamespace: true
    chart: datarepo-helm/charts/sqlbackup   # chart name
    version: 0.0.1
    missingFileHandler: Warn
    values:
      - psqlbackup/psqlbackup.yaml
