---
repositories:
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler

  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  createNamespace: true

# helm releases to be deployed
releases:
  - name: descheduler   # release name
    namespace: kube-system   # target namespace
    chart: descheduler/descheduler   # chart name
    version: v0.20.0 # chart version (note more recent charts break)
    missingFileHandler: Warn
    values:
      - schedule: "0 * * * *"

  - name: psqlbackup   # release name
    namespace: psqlbackup   # target namespace
    chart: datarepo-helm/sqlbackup   # chart name
    version: 0.0.2
    missingFileHandler: Warn
    values:
      - psqlbackup/psqlbackup.yaml

  - name: datarepomonitoring-secret   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/create-secret-manager-secret   # chart name
    version: 0.0.6
    missingFileHandler: Warn
    values:
      - datarepomonitoring/create-secret-manager-secret.yaml

  - name: datarepomonitoring-backend-config   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/backend-config   # chart name
    version: 0.1.0
    missingFileHandler: Warn

  - name: datarepo-monitoring-frontend-config   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/frontend-config   # chart name
    version: 0.1.0
    missingFileHandler: Warn

  - name: grafana-gcp-managed-cert   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/gcp-managed-cert   # chart name
    version: 0.1.3
    missingFileHandler: Warn
    values:
      - fullnameOverride: grafana-gcp-managed-cert
      - domainName: datarepo-grafana.terra.bio

  - name: prometheus-gcp-managed-cert   # release name
    namespace: monitoring   # target namespace
    chart: datarepo-helm/gcp-managed-cert   # chart name
    version: 0.1.3
    missingFileHandler: Warn
    values:
      - fullnameOverride: prometheus-gcp-managed-cert
      - domainName: datarepo-prometheus.terra.bio

  - name: datarepomonitoring   # release name
    namespace: monitoring   # target namespace
    chart: prometheus-community/kube-prometheus-stack   # chart name
    version: 13.13.0   # chart version pin
    missingFileHandler: Warn
    values:
      - datarepomonitoring/kube-prometheus-stack.yaml
