gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
     # GCP instance name.
    - instance: "jade-postgres-101-d0e234edfe378f09"
     # GCP project where the instance exists.
      project: "broad-jade-integration"
     # GCP region where the instance exists.
      region: "us-central1"
     # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-integration-4
  existingSecretKey: sa

datarepo-api:
  enabled: true
  image:
    tag: 492a5bf-develop
  env:
    googleProjectid:  broad-jade-int-4
    dbDatarepoUsername:  drmanager
    springProfilesActive:  google,cloudsql,integration
    dbStairwayUsername:  drmanager
    dbStairwayUri: jdbc:postgresql://integration-4-jade-gcloud-sqlproxy.integration-4:5432/stairway-4
    dbDatarepoUri: jdbc:postgresql://integration-4-jade-gcloud-sqlproxy.integration-4:5432/datarepo-4
    itJadeApiUrl: https://jade-4.datarepo-integration.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-integration-4"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"

datarepo-ui:
  enabled: true
  image:
    tag: broad-jade-my_2020-02-14_15-04-11
  proxyPass:
    status: http://integration-4-jade-datarepo-api.integration-4:8080/status
    swagger: http://integration-4-jade-datarepo-api.integration-4:8080/swagger-ui.html
    api: http://integration-4-jade-datarepo-api.integration-4:8080
  serviceAccount:
    create: true
  rbac:
    create: true

oidc-proxy:
  replicaCount: 1
  enabled: true
  env:
    proxyUrl: http://integration-4-jade-datarepo-ui.integration-4:80/
    proxyUrl2: http://integration-4-jade-datarepo-api.integration-4:8080/api
    proxyUrl3: http://integration-4-jade-datarepo-api.integration-4:8080/register
    logLevel: debug
    serverName: jade.datarepo-integration.broadinstitute.org
    remoteUserClaim: sub
    enableStackdriver: yes
    filter2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
  ingress:
    enabled: true
    annotations:
      globalStaticIpName: integration-ip-4
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingTlsSecret: oidc-tls-key
