gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
    - instance: "jade-postgres-11-3689a35c4c" # GCP instance name.
      # GCP project where the instance exists.
      project: "broad-jade-integration"
      # GCP region where the instance exists.
      region: "us-central1"
      # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-integration-1
  existingSecretKey: sa
  nodeSelector:
    cloud.google.com/gke-nodepool: integration-node
datarepo-api:
  enabled: true
  image:
    tag: 868bd4c-develop
  env:
    GOOGLE_PROJECTID: broad-jade-int-1
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql,integration
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://integration-1-jade-gcloud-sqlproxy.integration-1:5432/stairway-1
    DB_DATAREPO_URI: jdbc:postgresql://integration-1-jade-gcloud-sqlproxy.integration-1:5432/datarepo-1
    IT_JADE_API_URL: https://jade-1.datarepo-integration.broadinstitute.org
    DATAREPO_GCS_ALLOWREUSEEXISTINGBUCKETS: true
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-integration-1"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
  nodeSelector:
    cloud.google.com/gke-nodepool: integration-node
datarepo-ui:
  enabled: true
  image:
    tag: 62c6d24-develop
  proxyPass:
    status: http://integration-1-jade-datarepo-api.integration-1:8080/status
    swagger: http://integration-1-jade-datarepo-api.integration-1:8080/swagger-ui.html
    shutdown: http://integration-1-jade-datarepo-api.integration-1:8080/shutdown
    api: http://integration-1-jade-datarepo-api.integration-1:8080
  serviceAccount:
    create: true
  rbac:
    create: true
  nodeSelector:
    cloud.google.com/gke-nodepool: integration-node
oidc-proxy:
  enabled: true
  replicaCount: 1
  env:
    PROXY_URL: http://integration-1-jade-datarepo-ui.integration-1:80/
    PROXY_URL2: http://integration-1-jade-datarepo-api.integration-1:8080/api
    PROXY_URL3: http://integration-1-jade-datarepo-api.integration-1:8080/register
    LOG_LEVEL: debug
    SERVER_NAME: jade.datarepo-integration.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript
      application/x-javascript
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.global-static-ip-name: integration-ip-1
      networking.gke.io/managed-certificates: "integration-1-certificate"
    tls:
    - hosts:
      - jade-1.datarepo-integration.broadinstitute.org
    paths:
    - /*
    hosts:
    - jade-1.datarepo-integration.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  nodeSelector:
    cloud.google.com/gke-nodepool: integration-node
