gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
    - instance: "jade-postgres-11-8a00fd4d3b" # GCP instance name.
      # GCP project where the instance exists.
      project: "broad-jade-dev"
      # GCP region where the instance exists.
      region: "us-central1"
      # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-dev
  existingSecretKey: sa
datarepo-api:
  enabled: true
  image:
    tag: a8458909-develop
  env:
    SERVER_MAX_HTTP_HEADER_SIZE: "1048576"
    GOOGLE_ALLOWREUSEEXISTINGBUCKETS: true
    GOOGLE_ALLOWREUSEEXISTINGPROJECTS: true
    GOOGLE_FIRESTORERETRIES: 50
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql,dev
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://dev-jade-gcloud-sqlproxy.dev:5432/stairway
    DB_DATAREPO_URI: jdbc:postgresql://dev-jade-gcloud-sqlproxy.dev:5432/datarepo
    DATAREPO_DNSNAME: jade.datarepo-dev.broadinstitute.org
    IT_JADE_API_URL: https://jade.datarepo-dev.broadinstitute.org
    AZURE_CREDENTIALS_APPLICATIONID: 4ab53258-0938-4e70-a25c-757b02b2af5a
    AZURE_CREDENTIALS_HOMETENANTID: fad90753-2022-4456-9b0a-c7e5b934e408
    AZURE_SYNAPSE_WORKSPACENAME: tdr-synapse-east-us-ondemand.sql.azuresynapse.net
    AZURE_SYNAPSE_INITIALIZE: true
    AZURE_MONITORING_NOTIFICATIONAPPLICATIONID: /subscriptions/c5f8eca3-f512-48cb-b01f-f19f1af9014c/resourceGroups/terra-dev-audit-logs-rg/providers/Microsoft.Logic/workflows/terra-protected-data-slack-notification
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_0__REGION: eastus
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_0__TARGETSTORAGEACCOUNTRESOURCEID: /subscriptions/c5f8eca3-f512-48cb-b01f-f19f1af9014c/resourceGroups/terra-dev-protected-data-logs-rg/providers/Microsoft.Storage/storageAccounts/ltslogsdeveastus
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_1__REGION: eastus2
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_1__TARGETSTORAGEACCOUNTRESOURCEID: /subscriptions/c5f8eca3-f512-48cb-b01f-f19f1af9014c/resourceGroups/terra-dev-protected-data-logs-rg/providers/Microsoft.Storage/storageAccounts/ltslogsdeveastus2
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_2__REGION: centralus
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_2__TARGETSTORAGEACCOUNTRESOURCEID: /subscriptions/c5f8eca3-f512-48cb-b01f-f19f1af9014c/resourceGroups/terra-dev-protected-data-logs-rg/providers/Microsoft.Storage/storageAccounts/ltslogsdevcentralus
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_3__REGION: southcentralus
    AZURE_MONITORING_LOGCOLLECTIONCONFIGS_3__TARGETSTORAGEACCOUNTRESOURCEID: /subscriptions/c5f8eca3-f512-48cb-b01f-f19f1af9014c/resourceGroups/terra-dev-protected-data-logs-rg/providers/Microsoft.Storage/storageAccounts/ltslogsdevsthcntrlus
    FEATURES_SEARCH_API: enabled
    ELASTICSEARCH_HOSTNAME: 10.0.21.132
    RBS_ENABLED: true
    RBS_POOL_ID: datarepo_v3
    RBS_INSTANCE_URL: https://buffer.dsde-dev.broadinstitute.org
    SAM_OPERATION_TIMEOUT_SECONDS: 30
    TERRA_COMMON_TRACING_STACKDRIVER_EXPORT_ENABLED: false
    OPENCENCUS_SPRING_ENABLED: false
    GOOGLE_SECURE_FOLDER_RESOURCE_ID: "753276429356"
    GOOGLE_DEFAULT_FOLDER_RESOURCE_ID: "270278425081"
    USERMETRICS_BARDBASEPATH: https://terra-bard-dev.appspot.com
    OIDC_CLIENTID: bbd07d43-01cb-4b69-8fd0-5746d9a5c9fe
    OIDC_AUTHORITYENDPOINT: https://terradevb2c.b2clogin.com/terradevb2c.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_TDR/v2.0
    OIDC_ADDCLIENTIDTOSCOPE: true
    OIDC_EXTRAAUTHPARAMS: prompt=login
    SENTRY_ENVIRONMENT: development
    SENTRY_DSN: https://a3d46c70bbc74f32bfc5153fb8f915a6@o54426.ingest.sentry.io/4504044616089600
    DUOS_SYNCUSERS_SCHEDULE: "@hourly"
    DATAREPO_COMPACTIDPREFIXALLOWLIST_0_: foo.0
    TPS_BASE_PATH: https://tps.dsde-dev.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-dev"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
  existingSecretAzure: "azure-dev"
  existingApplicationSecretSecretKey: "applicationsecret"
  existingSynapseUserSecretKey: "synapse-us-east-sql-admin-user"
  existingSynapsePasswordSecretKey: "synapse-us-east-sql-admin-password"
  existingSynapseEncryptionKeySecretKey: "synapse-us-east-encryption-key"
  replicaCount: 3
  existingSecretRBS: "rbs-sa-dev"
  existingRBSSecretKey: "rbsserviceaccount"
datarepo-ui:
  enabled: true
  image:
    tag: 83e83f4-develop
  proxyPass:
    status: http://dev-jade-datarepo-api.dev:8080/status
    swagger: http://dev-jade-datarepo-api.dev:8080/swagger-ui.html
    api: http://dev-jade-datarepo-api.dev:8080
  serviceAccount:
    create: true
  rbac:
    create: true
oidc-proxy:
  enabled: true
  env:
    PROXY_URL: http://dev-jade-datarepo-ui.dev:8080/
    PROXY_URL2: http://dev-jade-datarepo-api.dev:8080/api
    PROXY_URL3: http://dev-jade-datarepo-api.dev:8080/ga4gh
    PROXY_PATH3: /ga4gh
    LOG_LEVEL: info
    SERVER_NAME: jade.datarepo-dev.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript
      application/x-javascript
  ingress:
    sslPolicy: global-ssl-policy
    enabled: true
    domainName: jade.datarepo-dev.broadinstitute.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: jade-k8-100
      networking.gke.io/v1beta1.FrontendConfig: dev-jade-oidc-proxy
    paths:
    - /*
    hosts:
    - jade.datarepo-dev.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
de-elasticsearch:
  enabled: true
