gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
    - instance: "jade-postgres-11-8a00fd4d3b" # GCP instance name.
      # GCP project where the instance exists.
      project: "broad-jade-dev"
      # GCP region where the instance exists.
      region: "us-central1"
      # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-dev
  existingSecretKey: sa
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
datarepo-api:
  enabled: true
  image:
    tag: 732b5a9-develop
  env:
    GOOGLE_PROJECTID: broad-jade-dev
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql,dev
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://dev-jade-gcloud-sqlproxy.dev:5432/stairway
    DB_DATAREPO_URI: jdbc:postgresql://dev-jade-gcloud-sqlproxy.dev:5432/datarepo
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-dev"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
datarepo-ui:
  enabled: true
  image:
    tag: 4b59397-develop
  proxyPass:
    status: http://dev-jade-datarepo-api.dev:8080/status
    swagger: http://dev-jade-datarepo-api.dev:8080/swagger-ui.html
    shutdown: http://dev-jade-datarepo-api.dev:8080/shutdown
    api: http://dev-jade-datarepo-api.dev:8080
  serviceAccount:
    create: true
  rbac:
    create: true
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
oidc-proxy:
  enabled: true
  env:
    PROXY_URL: http://dev-jade-datarepo-ui.dev:8080/
    PROXY_URL2: http://dev-jade-datarepo-api.dev:8080/api
    PROXY_URL3: http://dev-jade-datarepo-api.dev:8080/register
    LOG_LEVEL: debug
    SERVER_NAME: jade.datarepo-dev.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript
      application/x-javascript
  ingress:
    enabled: true
    domainName: jade.datarepo-dev.broadinstitute.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: jade-k8-100
    tls:
    - hosts:
      - jade.datarepo-dev.broadinstitute.org
    paths:
    - /*
    hosts:
    - jade.datarepo-dev.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
