gcloud-sqlproxy:
  enabled: true
  cloudsql:
    instances:
    - instance: "jade-postgres-11-8a00fd4d3b" # GCP instance name.
      # GCP project where the instance exists.
      project: "broad-jade-dev"
      # GCP region where the instance exists.
      region: "us-central1"
      # Port number for the proxy to expose for this instance.
      port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  existingSecret: sqlproxy-sa-dev
  existingSecretKey: sa
datarepo-api:
  enabled: true
  image:
    tag: f5af9f90-develop
  env:
    GOOGLE_FIRESTORERETRIES: 50
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql,dev
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://dev-jade-gcloud-sqlproxy.dev:5432/stairway
    DB_DATAREPO_URI: jdbc:postgresql://dev-jade-gcloud-sqlproxy.dev:5432/datarepo
    DATAREPO_DNSNAME: jade.datarepo-dev.broadinstitute.org
    IT_JADE_API_URL: https://jade.datarepo-dev.broadinstitute.org
    AZURE_CREDENTIALS_APPLICATIONID: 22cb243c-f1a5-43d8-8f12-6566bcce6542
    AZURE_CREDENTIALS_HOMETENANTID: fad90753-2022-4456-9b0a-c7e5b934e408
    FEATURES_SEARCH_API: enabled
    ELASTICSEARCH_HOSTNAME: 10.0.21.132
    RBS_ENABLED: true
    RBS_POOL_ID: datarepo_v3
    RBS_INSTANCE_URL: https://buffer.dsde-dev.broadinstitute.org
    TERRA_COMMON_TRACING_STACKDRIVER_EXPORT_ENABLED: false
    OPENCENCUS_SPRING_ENABLED: false
  GOOGLE_SECURE_FOLDER_RESOURCE_ID: 753276429356
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-dev"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
  existingSecretAzure: "azure-dev"
  existingApplicationSecretSecretKey: "applicationsecret"
  existingSynapseUserSecretKey: "synapse-us-east-sql-admin-user"
  existingSynapsePasswordSecretKey: "synapse-us-east-sql-admin-password"
  replicaCount: 3
  existingSecretRBS: "rbs-sa-dev"
  existingRBSSecretKey: "rbsserviceaccount"
datarepo-ui:
  enabled: true
  image:
    tag: c889159-develop
  proxyPass:
    status: http://dev-jade-datarepo-api.dev:8080/status
    swagger: http://dev-jade-datarepo-api.dev:8080/swagger-ui.html
    shutdown: http://dev-jade-datarepo-api.dev:8080/shutdown
    api: http://dev-jade-datarepo-api.dev:8080
  serviceAccount:
    create: true
  rbac:
    create: true
oidc-proxy:
  enabled: true
  env:
    PROXY_URL: http://dev-jade-datarepo-ui.dev:8080/
    PROXY_URL2: http://dev-jade-datarepo-api.dev:8080/api
    PROXY_URL3: http://dev-jade-datarepo-api.dev:8080/ga4gh
    PROXY_PATH3: /ga4gh
    LOG_LEVEL: debug
    SERVER_NAME: jade.datarepo-dev.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript
      application/x-javascript
  ingress:
    sslPolicy: global-ssl-policy
    enabled: true
    domainName: jade.datarepo-dev.broadinstitute.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: jade-k8-100
      networking.gke.io/v1beta1.FrontendConfig: dev-jade-oidc-proxy
    paths:
    - /*
    hosts:
    - jade.datarepo-dev.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
de-elasticsearch:
  enabled: true
