---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-operator
  namespace: elastic-system
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: elastic-pod-running-policy
  namespace: elastic-system
  labels:
    name: elasticoperator
spec:
  privileged: false  # Don't allow privileged pods!
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elastic-use-pod-security-policy-role
  namespace: elastic-system
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ["use"]
  resourceNames:
    - elastic-pod-running-policy
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elastic-sa-use-pod-security-policy
  namespace: elastic-system
subjects:
- kind: ServiceAccount
  name: elastic-operator
roleRef:
  kind: Role
  name: use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
