## ps env specific skaffold.yaml
apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: gcr.io/broad-jade-dev/jade-data-repo
    jib:
      args:
      - jib
      type: gradle
deploy:
  helm:
    flags:
      upgrade:
        - --install
        - --debug
    releases:
# create secrets
    - name: ps-jade-create-secret-manager-secret
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/create-secret-manager-secret-0.0.6/create-secret-manager-secret-0.0.6.tgz
      version: 0.0.6
      namespace: ps
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ps/create-secret-manager-secret.yaml
# gcp sqlproxy
    - name: ps-jade-gcloud-sqlproxy
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/gcloud-sqlproxy-0.19.7/gcloud-sqlproxy-0.19.7.tgz
      version: 0.19.7
      namespace: ps
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ps/gcloud-sqlproxy.yaml
# datarepo-api
    - name: ps-jade-datarepo-api
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/datarepo-api-0.0.25/datarepo-api-0.0.25.tgz
      version: 0.0.25
      namespace: ps
      remote: true
      values:
        imageName: gcr.io/broad-jade-dev/jade-data-repo
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ps/datarepo-api.yaml
# datarepo-ui
    - name: ps-jade-datarepo-ui
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/datarepo-ui-0.0.13/datarepo-ui-0.0.13.tgz
      version: 0.0.13
      namespace: ps
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ps/datarepo-ui.yaml
# oidc-proxy
    - name: ps-jade-oidc-proxy
      chartPath: https://github.com/broadinstitute/datarepo-helm/releases/download/oidc-proxy-0.0.16/oidc-proxy-0.0.16.tgz
      version: 0.0.16
      namespace: ps
      remote: true
      valuesFiles:
      - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ps/oidc-proxy.yaml
