---
gcloud-sqlproxy:
  enabled: true
  googleServiceAccount: nm-proxy-sa@broad-jade-dev.iam.gserviceaccount.com
  cloudsql:
    instances:
      # GCP instance name.
      - instance: "jade-postgres-11-8a00fd4d3b"
        # GCP project where the instance exists.
        project: "broad-jade-dev"
        # GCP region where the instance exists.
        region: "us-central1"
        # Port number for the proxy to expose for this instance.
        port: 5432
  rbac:
    create: true
  networkPolicy:
    enabled: false
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node

datarepo-api:
  enabled: true
  image:
    tag: 6aca04a-develop
  env:
    GOOGLE_PROJECTID: broad-jade-dev
    GOOGLE_SINGLEDATAPROJECTID: broad-jade-nm
    DB_DATAREPO_USERNAME: drmanager
    SPRING_PROFILES_ACTIVE: google,cloudsql,dev,nm
    DB_STAIRWAY_USERNAME: drmanager
    DB_STAIRWAY_URI: jdbc:postgresql://nm-jade-gcloud-sqlproxy.nm:5432/stairway-nm
    DB_DATAREPO_URI: jdbc:postgresql://nm-jade-gcloud-sqlproxy.nm:5432/datarepo-nm
    dbStairwayForceclean: true
    dbMigrateDropallonstart: true
    DATAREPO_GCS_ALLOWREUSEEXISTINGBUCKETS: true
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  existingSecretDB: "database-pwd-nm"
  existingDatarepoDbSecretKey: "datarepopassword"
  existingStairwayDbSecretKey: "stairwaypassword"
  existingSecretSA: "jade-sa"
  existingServiceAccountSecretKey: "datareposerviceaccount"
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node

datarepo-ui:
  enabled: true
  image:
    tag: fcd1b81-develop
  proxyPass:
    status: http://nm-jade-datarepo-api.nm:8080/status
    shutdown: http://nm-jade-datarepo-api.nm:8080/shutdown
    swagger: http://nm-jade-datarepo-api.nm:8080/swagger-ui.html
    api: http://nm-jade-datarepo-api.nm:8080
  serviceAccount:
    create: true
  rbac:
    create: true
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node

oidc-proxy:
  enabled: true
  env:
    PROXY_URL: http://nm-jade-datarepo-ui.nm:8080/
    PROXY_URL2: http://nm-jade-datarepo-api.nm:8080/api
    PROXY_URL3: http://nm-jade-datarepo-api.nm:8080/register
    LOG_LEVEL: debug
    SERVER_NAME: jade.datarepo-dev.broadinstitute.org
    REMOTE_USER_CLAIM: sub
    ENABLE_STACKDRIVER: yes
    FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
  ingress:
    enabled: true
    domainName: jade-nm.datarepo-dev.broadinstitute.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: jade-dev-nm
    tls:
      - hosts:
          - jade-nm.datarepo-dev.broadinstitute.org
    paths:
      - /*
    hosts:
      - jade-nm.datarepo-dev.broadinstitute.org
  serviceAccount:
    create: true
  rbac:
    create: true
    pspEnabled: true
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
