---
apiVersion: v1
kind: Namespace
metadata:
  name: ms
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ms-secrets
  namespace: ms
spec:
  releaseName: secrets
  targetNamespace: ms
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm/
    name: create-secret-manager-secret
    version: 0.0.4
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ms/msSecrets.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ms-datarepo
  namespace: ms
spec:
  releaseName: ms-jade
  targetNamespace: ms
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm/
    name: datarepo
    version: 0.0.4
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ms/msDeployment.yaml
