---
repoServer:
  serviceAccount:
    create: true
    name: argocd-repo-server
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
redis:
  enabled: flase
redis-ha:
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
  enabled: true
  serviceAccount:
    create: true
    name: redis-sa
configs:
  secret:
    createSecret: false
server:
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
  extraArgs:
    - --insecure
  config:
    url: https://argocd.datarepo-dev.broadinstitute.org
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 3fea9f34762c0e2f127d
            clientSecret: $dex.github.clientSecret
            orgs:
            - name: DataBiosphere
            - name: broadinstitute
  service:
    annotations:
      beta.cloud.google.com/backend-config: '{"ports": {"80":"ip-whitelist-backend-config"}}'
    type: NodePort  # Required to enable forwarding from Ingress/LB to service
  ingress:
    enabled: true
    tls:
      - hosts:
          - argocd.datarepo-dev.broadinstitute.org
    paths:
      - /*
    hosts:
      - argocd.datarepo-dev.broadinstitute.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: argocd-k8-100
      kubernetes.io/ingress.allow-http: "false"  # Disable http traffic
      networking.gke.io/managed-certificates: "argocd-certificate"
  rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      g, broadinstitute:DSP DevOps, role:admin
      g, broadinstitute:jade_prod, role:admin
      g, broadinstitute:jadeteam, role:admin
controller:
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
dex:
  nodeSelector:
    cloud.google.com/gke-nodepool: dev-node
