---
repoServer:
  serviceAccount:
    create: true
    name: argocd-repo-server
redis:
  enabled: flase
redis-ha:
  enabled: true
  serviceAccount:
    create: true
    name: redis-sa
configs:
  secret:
    createSecret: false
server:
  name: jade
  image:
    tag: v1.5.2
  extraArgs:
    - --insecure  # Required to enable TLS termination at Ingress/LB
  config:  # SSO
    url: https://argocd.datarepo-dev.broadinstitute.org
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 8b0d231f2555f04bff12
            clientSecret: $dex.github.clientSecret
            orgs:
            - name: DataBiosphere
            - name: broadinstitute
  service:
    type: NodePort  # Required to enable forwarding from Ingress/LB to service
  ingress:
    enabled: true
    path: /*
    tls:
      - hosts:
        - argocd.datarepo-dev.broadinstitute.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: argocd-k8-100
      kubernetes.io/ingress.allow-http: "false"  # Disable http traffic
      networking.gke.io/managed-certificates: "argocd-certificate"
