---
secrets:
  - secretName: argocd-secret
    vals:
      - kubeSecretKey: admin.password
        path: secret/dsde/datarepo/dev/argocd
        vaultKey: admin.password
      - kubeSecretKey: dex.github.clientSecret
        path: secret/dsde/datarepo/dev/argocd
        vaultKey: dex.github.clientSecret
      - kubeSecretKey: server.secretkey
        path: secret/dsde/datarepo/dev/argocd
        vaultKey: server.secretkey
