---
repositories:
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler

# helm releases to be deployed
releases:
  - name: descheduler   # release name
    namespace: kube-system   # target namespace
    chart: descheduler/descheduler   # chart name
    version: v0.20.0 # chart version (note more recent charts break)
    missingFileHandler: Warn
    values:
      - schedule: "0 * * * *"
