# single env example file
# helm file dependencies
# helm plugin install https://github.com/databus23/helm-diff
# repositories to be installed
repositories:
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler

helmDefaults:
  createNamespace: true

environments:
  integration-1:
  integration-2:
  integration-3:
  integration-4:
  integration-5:
  integration-6:

# helm releases to be deployed
### Environment-specific resources
{{- if ne .Environment.Name "default" }} # Only render these if an environment is given with -e
releases:
  - name: descheduler   # release name
    namespace: kube-system   # target namespace
    chart: descheduler/descheduler   # chart name
    version: v0.20.0 # chart version (note more recent charts break)
    missingFileHandler: Warn
    values:
      - schedule: "0 * * * *"
  - name: {{ .Environment.Name }}-jade-create-secret-manager-secret    # release name
    namespace: {{ .Environment.Name }}   # target namespace
    chart: datarepo-helm/create-secret-manager-secret   # chart name
    version: 0.0.6   #    Chart version
    missingFileHandler: Warn
    values:
      - {{ .Environment.Name }}/create-secret-manager-secret.yaml      # Value files passed via --values
  - name: {{ .Environment.Name }}-jade-gcloud-sqlproxy    # release name
    namespace: {{ .Environment.Name }}   # target namespace
    chart: datarepo-helm/gcloud-sqlproxy   # chart name
    version: 0.19.7 #    Chart version
    missingFileHandler: Warn
    values:
      - {{ .Environment.Name }}/gcloud-sqlproxy.yaml    # Value files passed via --values
  - name: {{ .Environment.Name }}-jade-datarepo-api   # name of this release
    namespace: {{ .Environment.Name }}   # target namespace
    chart: datarepo-helm/datarepo-api   # the chart name
    version: 0.0.96    # chart version
    missingFileHandler: Warn
    values:
      - {{ .Environment.Name }}/datarepo-api.yaml   # Value files passed via --values
  - name: {{ .Environment.Name }}-jade-datarepo-ui   # name of this release
    namespace: {{ .Environment.Name }}   # target namespace
    chart: datarepo-helm/datarepo-ui   # the chart name
    version: 0.0.77    # chart version
    missingFileHandler: Warn
    values:
      - {{ .Environment.Name }}/datarepo-ui.yaml   # Value files passed via --values
  - name: {{ .Environment.Name }}-jade-oidc-proxy   # name of this release
    namespace: {{ .Environment.Name }}   # target namespace
    chart: datarepo-helm/oidc-proxy   # the chart name
    version: 0.0.23    # chart version
    missingFileHandler: Warn
    values:
      - {{ .Environment.Name }}/oidc-proxy.yaml   # Value files passed via --values
{{- end -}}
