---
name: Yaml Lint
on:
  pull_request:
    branches:
      - master
jobs:
  lintAllTheThings:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: broadinstitute/action-yamllint@v1
        with:
          config_file: .github/yamllint.yaml
          file_or_dir: alpha/*/ dev/*/ fakeprod/ integration/*/ perf/*/ prod/* staging/*/ scripts/
